### ISSUE TITLE
Move the bin directory to the root of the project so it can be easily included in other projects

### ISSUE THREAD

**Issue by zero2one** [druleton/druleton#26]
The bin directory is now included in project repositories. As the content of the `bin` directory is not to be changed within a project, that directory does not need to be part of the project.

The druleton/druleton repository needs to contain only the content within the bin directory. This will make ite easier to include it as a git-submodule so it can be used without having to maintain a copy in the actual project repo.
- [x] Move the config & project directory to a template directory within the bin directory.
- [x] Delete all directories except the bin directory
- [x] Move all content from within the bin directory to the root of the druleton/druleton project.
- [x] Update the init script so it checks if the config & project directories exists, if not create them using the template files.
- [x] Update documentation how to include the druleton/druleton repo in a project as bin
  `bash
  $ git submodule add https://github.com/druleton/druleton bin
  $ git submodule init
  $ git submodule update
  `
- [x] Add/update documentation.

**Comment by jover** [comment]
Currently I have set Drupal Skeleton to be a Git Submodule of a project.
Unfortunately, at least as far as I know, it's not possible to checkout a submodule in the root of your own project, so I ended up creating a symbolic link to the bin folder of the Drupal Skeleton submodule.

So in the root of the project:
./bin -> ./drupal-skeleton/bin

This way, still the whole Drupal Skeleton code is checked out, but it's not necessary to commit the files in the bin folder of the Drupal Skeleton in your own project.

**Comment by zero2one** [comment]
I'm gonna cut out the bin directory of the drupal skeleton and put it in a separate repo called druleton/bin.

That will make it easier to include it as a submodule :-)

**Comment by zero2one** [comment]
See PR #41

**Comment by zero2one** [comment]
See PR #41.
